[package]
name = "euui"
description = "An Extended Universal Unique Identifier"
categories = ["encoding", "data-structures"]
keywords = ["EUUI", "identifier", "unique", "guid"]
license = "MIT"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.rand]
version = "0.9.0-alpha.1"